import 'package:nectar_ui_ux/models/items.dart';
import 'package:nectar_ui_ux/models/subItems.dart';

class SecondUtils {
  static List<Items> getMockedItems() {
    return [
      Items(
        itemsName: 'Fresh fruits and Vegetables',
        itemsImg: "https://www.foodnavigator.com/var/wrbm_gb_food_pharma/storage/images/5/9/8/3/2063895-1-eng-GB/Cellresin-Technologies-talks-shelf-life.jpg",
        borderColor: '0xFFEC407A',
        backColor: '0xFFF8BBD0',
        subItems: [
          SubItems(
            itemsName: 'Capsicum',
            itemsImg: "https://us.123rf.com/450wm/spamas/spamas1908/spamas190801343/128346918-green-pepper-full-depth-of-field-on-white-background.jpg?ver=6",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '1 kg',
          ),
          SubItems(
            itemsName: 'Ladies Finger',
            itemsImg: "https://t3.ftcdn.net/jpg/00/93/87/58/360_F_93875874_u9pFhj8A6MNFchnUgNTAAAWnmIA4F4Y0.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '3 kg',
          ),
          SubItems(
            itemsName: 'Cauliflower',
            itemsImg: "https://thumbs.dreamstime.com/b/cauliflower-isolated-white-background-top-view-cauliflower-isolated-white-background-top-view-152592460.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '4 kg',
          ),
          SubItems(
            itemsName: 'Eggplant',
            itemsImg: "https://thumbs.dreamstime.com/b/whole-aubergine-eggplant-isolate-white-background-three-vegetables-130304945.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '2 kg',
          ),
          SubItems(
            itemsName: 'Onion',
            itemsImg: "https://produits.bienmanger.com/36700-0w470h470_Organic_Red_Onion_From_Italy.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '2.99',
            itemDescription: '3 kg',
          ),
          SubItems(
            itemsName: 'Beetroot',
            itemsImg: "https://m.media-amazon.com/images/I/616PXhYj8iL._SL1000_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '5 kg',
          ),
          SubItems(
            itemsName: 'Pumpkin',
            itemsImg: "https://images.othoba.com/images/thumbs/0305693_f-1-hybrid-indian-green-pumpkin-seeds-intact-packet-5-gm.jpeg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '2 kg',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Cooking Oil and Ghee",
        itemsImg: "https://rootsthelegacy.com/uploads/category_image/category_34.jpg",
        borderColor: '0xFFEF5350',
        backColor: '0xFFFFCDD2',
        subItems: [
          SubItems(
            itemsName: 'Fortune',
            itemsImg: "https://5.imimg.com/data5/SN/ME/MY-12514960/edibile-oil-500x500.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '5 L',
          ),
          SubItems(
            itemsName: 'Gemeni',
            itemsImg: "https://www.jiomart.com/images/product/600x600/490012721/gemini-refined-enriched-with-nutri-v-sunflower-oil-15-l-product-images-o490012721-p490012721-0-202203170754.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '5 L',
          ),
          SubItems(
            itemsName: 'Afia',
            itemsImg: "https://m.media-amazon.com/images/I/61w3aSpYmgL.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '1 L',
          ),
          SubItems(
            itemsName: 'Emami',
            itemsImg: "https://www.bigbasket.com/media/uploads/p/l/40007923_4-emami-healthy-tasty-kachi-ghani-mustard-oil.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '1 L',
          ),
          SubItems(
            itemsName: 'Amul Ghee',
            itemsImg: "https://m.media-amazon.com/images/I/81I6KRoU+HL._SL1500_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '2.99',
            itemDescription: '500 g',
          ),
          SubItems(
            itemsName: 'Safolla',
            itemsImg: "https://2.imimg.com/data2/OW/NJ/MY-3998144/2006020900280402-500x500.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '5 L',
          ),
          SubItems(
            itemsName: 'Patanjali',
            itemsImg: "https://thingsinindia.in/wp-content/uploads/2018/05/patanjanli.png-300x254.png",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '5 L',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Meat and Fish",
        itemsImg: "https://foodsafetyhelpline.com/wp-content/uploads/2018/12/Meat-Products.jpg",
        borderColor: '0xFFFF8A65',
        backColor: '0xFFFFCCBC',
        subItems: [
          SubItems(
            itemsName: 'Pork',
            itemsImg: "https://media.istockphoto.com/photos/sliced-raw-pork-meat-with-rosemary-isolated-on-white-background-top-picture-id1162194568?k=20&m=1162194568&s=612x612&w=0&h=-a7tsUFBIWw-xM7ZCxtzeqfhKxrdeFjANZO-1q8CyJM=",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '5 kg',
          ),
          SubItems(
            itemsName: 'Beef',
            itemsImg: "https://thumbs.dreamstime.com/b/raw-beaf-steaks-parsley-white-background-114278638.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '5 kg',
          ),
          SubItems(
            itemsName: 'Lamb',
            itemsImg: "https://wbldc.in/wp-content/uploads/2021/04/mutton-lamb-meat.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '6 kg',
          ),
          SubItems(
            itemsName: 'Goat',
            itemsImg: "https://media.istockphoto.com/photos/piece-of-fresh-goat-meat-picture-id176101808?k=20&m=176101808&s=170667a&w=0&h=nLuCjSJ72zpEbwE3A2cL6hzZSkvrdoQFGptmOHGdWgo=",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '7 kg',
          ),
          SubItems(
            itemsName: 'Chicken',
            itemsImg: "https://5.imimg.com/data5/XM/PP/MY-44080452/country-chicken-meat-500x500.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '5 kg',
          ),
          SubItems(
            itemsName: 'Tuna',
            itemsImg: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Bluefin-big.jpg/640px-Bluefin-big.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '2 kg',
          ),
          SubItems(
            itemsName: 'Mackerel',
            itemsImg: "https://content.jdmagicbox.com//rep/b2b/indian-mackerel/indian-mackerel-4.jpg?impolicy=queryparam&im=Resize=(360,360),aspect=fit",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '5 kg',
          ),
          SubItems(
            itemsName: 'Sardines',
            itemsImg: "https://5.imimg.com/data5/SELLER/Default/2021/2/OU/MK/WL/121262781/sardine-fish-500x500.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '10 kg',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Bakery and Snacks",
        itemsImg: "https://i2.wp.com/xtalks.com/wp-content/uploads/2019/11/Revied-Three-Snacks3.jpg?fit=1000%2C600&ssl=1",
        borderColor: '0xFFFFA726',
        backColor: '0xFFFFE0B2',
        subItems: [
          SubItems(
            itemsName: 'Rusk Toast',
            itemsImg: "https://5.imimg.com/data5/WJ/LI/MY-52324712/rusk-500x500.jpeg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '10 Packets',
          ),
          SubItems(
            itemsName: 'Bread and Buns',
            itemsImg: "https://c4.wallpaperflare.com/wallpaper/866/878/494/basket-mac-bread-buns-wallpaper-thumb.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '1.99',
            itemDescription: '10 kg',
          ),
          SubItems(
            itemsName: 'Cakes',
            itemsImg: "https://previews.123rf.com/images/maxpayne222/maxpayne2221210/maxpayne222121000040/15703284-schokoladenkuchen-isoliert-auf-wei%C3%9Fem-hintergrund.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '8.99',
            itemDescription: '10 pcs',
          ),
          SubItems(
            itemsName: 'Waffle',
            itemsImg: "https://static.toiimg.com/thumb/52502965.cms?imgsize=46435&width=800&height=800",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '5 Packets',
          ),
          SubItems(
            itemsName: 'Pastry',
            itemsImg: "https://www.bigbasket.com/media/uploads/p/l/700107520_1-jain-bakery-pastry-pineapple.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '1 pc',
          ),
          SubItems(
            itemsName: 'Muffins and Cup Cakes',
            itemsImg: "https://st.depositphotos.com/1367205/1262/i/950/depositphotos_12629325-stock-photo-muffins-on-a-white-background.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '5 pcs',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Dairy and Eggs",
        itemsImg: "https://simplyfresh.info/wp-content/uploads/2015/09/simply-handlingdairy.jpg",
        borderColor: '0xFFFFCA28',
        backColor: '0xFFFFF9C4',
        subItems: [
          SubItems(
            itemsName: 'Duck Eggs',
            itemsImg: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToRMWx_B_d5Gd__l42A8ulIxJiDuePyyRpVoSkVIe_gS9AypGz7kavl2P6ebfF7SpZk7g&usqp=CAU",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '10 Pcs',
          ),
          SubItems(
            itemsName: 'Chicken Eggs',
            itemsImg: "https://5.imimg.com/data5/WY/OA/MY-35471420/country-chicken-egg-500x500.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '10 Pcs',
          ),
          SubItems(
            itemsName: 'Milk',
            itemsImg: "https://static.turbosquid.com/Preview/2019/11/15__02_27_35/1.jpg3ADAA9DC-208D-4896-925C-FD3EB5BC3D4DLarge.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '10 Packets',
          ),
          SubItems(
            itemsName: 'Cream',
            itemsImg: "https://5.imimg.com/data5/SELLER/Default/2020/12/FX/UU/PU/8616377/screenshot-636--500x500.png",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '1 Packet',
          ),
          SubItems(
            itemsName: 'Butter',
            itemsImg: "https://www.jiomart.com/images/product/original/490001392/amul-butter-500-g-carton-product-images-o490001392-p490001392-0-202203152128.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '10 Packets',
          ),
          SubItems(
            itemsName: 'Yogurt',
            itemsImg: "https://crystalcreamery.com/assets/image-cache/uploads/images/products/yogurt/yogurt-plain-1480x1452.327c2658.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '10 Pcs',
          ),
          SubItems(
            itemsName: 'Cheese',
            itemsImg: "https://www.bigbasket.com/media/uploads/p/xxl/30002338_11-britannia-cheese-block.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '10 Pcs',
          ),
          SubItems(
            itemsName: 'Custard',
            itemsImg: "https://m.media-amazon.com/images/I/71qRlqiaHzL._SX522_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '10 Pcs',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Beverages",
        itemsImg: "https://5.imimg.com/data5/SELLER/Default/2020/10/NP/NQ/FF/115160227/q-500x500.png",
        borderColor: '0xFFD4E157',
        backColor: '0xFFF0F4C3',
        subItems: [
          SubItems(
            itemsName: 'Coca-Cola',
            itemsImg: "https://m.media-amazon.com/images/I/71OhN3v9JTL._SX522_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Lemonade',
            itemsImg: "https://www.kroger.com/product/images/large/front/0002500005801",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Mello Yello',
            itemsImg: "https://m.media-amazon.com/images/I/71YxsSQIP8L._SL1500_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Pepsi',
            itemsImg: "https://www.jiomart.com/images/product/original/490004176/pepsi-2-l-product-images-o490004176-p490004176-0-202203170742.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '3.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Thumbs up',
            itemsImg: "https://m.media-amazon.com/images/I/71h7T4jsgzL._SL1500_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '7.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Limca',
            itemsImg: "https://www.netmeds.com/images/product-v1/600x600/911120/limca_soft_drink_1_25_litre_0_0.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '6.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Fanta',
            itemsImg: "https://images.qubitlink.com/media/product/1208898312/31/Fanta-Soft-Drink---Orange-2.25-Itr.jpg_._500_500",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '4.99',
            itemDescription: '2 L',
          ),
          SubItems(
            itemsName: 'Frooti',
            itemsImg: "https://cdn.shopaccino.com/pantryhub/products/ph0ca072-1-886130_m.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            subItems: [],
            price: '5.99',
            itemDescription: '2 L',
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "Chocolates",
        itemsImg: "https://i.ytimg.com/vi/pyLX3dMsrvk/maxresdefault.jpg",
        borderColor: '0xFF66BB6A',
        backColor: '0xFFDCEDC8',
        subItems: [
          SubItems(
              itemsName: "Cadbury",
              itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/cadbury-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
              price: "3.99",
              itemDescription: "4 packs",
              subItems: [],
          ),
          SubItems(
            itemsName: "Nestle",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/nestle-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "4.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Amul",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/amul-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "3.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Parle",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/parle-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "2.99",
            itemDescription: "3 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Mars",
            itemsImg: "https://www.pelignafood.it/3226-thickbox_default/mars-caramel-and-milk-chocolate-bars-51gr-display-of-32pcs.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "7.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Ferrero Rocher",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/ferrero-rocher-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "15.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Fabelle",
            itemsImg: "https://m.media-amazon.com/images/I/71rLywCYK0L._SX522_.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "14.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Lindt",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/lindt-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "10.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
          SubItems(
            itemsName: "Campco",
            itemsImg: "https://floweraura-blog-img.s3.ap-south-1.amazonaws.com/campco-chocolates.jpg",
            borderColor: "0xFFD6D6D",
            backColor: '0xFFFFFFFF',
            price: "7.99",
            itemDescription: "5 packs",
            subItems: [],
          ),
        ],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "2",
        itemsImg: "https://3.imimg.com/data3/VS/UT/MY-13965561/groceries-500x500.png",
        borderColor: '0xFF4DB6AC',
        backColor: '0xFFB2DFDB',
        subItems: [],
        price: '',
        itemDescription: '',
      ),
      Items(
        itemsName: "3",
        itemsImg: "https://img2.exportersindia.com/product_images/bc-full/2022/2/5104794/personal-care-products-1501500793-3183216.jpeg",
        borderColor: '0xFF00ACC1',
        backColor: '0xFFE0F7FA', subItems: [], price: '', itemDescription: '',
      ),
      Items(
        itemsName: "4",
        itemsImg: "https://www.kindpng.com/picc/m/241-2413612_grocery-png-image-high-quality-indian-grocery-transparent.png",
        borderColor: '0xFF0288D1',
        backColor: '0xFFE1F5FE', subItems: [], price: '', itemDescription: '',
      ),
    ];
  }
}