import 'package:nectar_ui_ux/models/category.dart';

class Utils{

  static List<Category> getMockedCategories() {
    return [
      Category(
          name: "Mango",
          imgName: "assets/image/mango.jpg",
          price: "4.99",
          subCategories: [],
          description: '7 pcs',
        vegImg: 'https://m.media-amazon.com/images/I/51IqaEYX9PL._SL1000_.jpg',
        vegDescription: '2 pc',
        vegPrice: '3.99',
        vegName: 'Red Capsicum',
        meatDesc: '1 kg',
        meatName: 'Beaf Bone',
        meatPrice: '3.99',
        meatImg: 'https://media.istockphoto.com/photos/raw-caw-bones-isolated-on-white-background-picture-id891359890?k=20&m=891359890&s=612x612&w=0&h=b5UFE4VSTck1ZKRnWnNmwBjryu5DdHmwNa-8a7v47H8=',
        nameGrocery: 'Pulses',
        imgGrocery: 'https://goqii.com/blog/wp-content/uploads/Why-Pulses-Are-Good-For-You.jpg',
        colorCode: '0XFFF8BBD0',
        descriptionGrocery: 'Pulses are the edible seeds of plants in the legume family. Pulses grow in pods and come in a variety of shapes, sizes and colors. The United Nations Food and Agriculture Organization (FAO) recognizes 11 types of pulses: dry beans, dry broad beans, dry peas, chickpeas, cow peas, pigeon peas, lentils, Bambara beans, vetches, lupins and pulses nes (not elsewhere specified – minor pulses that don’t fall into one of the other categories).',
      ),
      Category(
          name: "Apple",
          imgName: "assets/image/apple.jpg",
          price: "7.99",
          subCategories: [],
          description: '1 kg',
        vegImg: 'https://media.istockphoto.com/photos/tomato-isolated-on-white-background-picture-id466175630?k=6&m=466175630&s=612x612&w=0&h=fu_mQBjGJZIliOWwCR0Vf2myRvKWyQDsymxEIi8tZ38=',
        vegDescription: '4 kg',
        vegPrice: '7.99',
        vegName: 'Tomato',
        meatDesc: '1 kg',
        meatName: 'Broiler Chicken ',
        meatPrice: '2.99',
        meatImg: 'https://www.nepalitimes.com/wp-content/uploads/2018/05/page-8-9a-2.jpg',
        nameGrocery: 'Rice',
        imgGrocery: 'https://freshon.in/wp-content/uploads/2020/10/yXVnjEL3MW-1-scaled.jpg',
        colorCode: '0xFFEF9A9A',
        descriptionGrocery: 'Rice is the seed of the grass species Oryza sativa or less commonly Oryza glaberrima. The name wild rice is usually used for species of the genera Zizania and Porteresia, both wild and domesticated, although the term may also be used for primitive or uncultivated varieties of Oryza.',
      ),
      Category(
          name: "Banana",
          imgName: "assets/image/banana.jpg",
          price: "5.99",
          subCategories: [],
          description: '12 pcs',
        vegImg: 'https://www.foodchamps.org/wp-content/uploads/2021/08/Red-Onion.jpg',
        vegDescription: '2 kg',
        vegPrice: '3.99',
        vegName: 'Onion',
        meatDesc: '2 kg',
        meatName: 'Duck Meat',
        meatPrice: '4.99',
        meatImg: 'https://media.istockphoto.com/photos/raw-whole-duck-isolated-on-white-picture-id1026181690?k=20&m=1026181690&s=612x612&w=0&h=siq3bZuWLVuCWsjk6708ZqeAVPJ7Spn1Nmi1QHGvyoI=',
        nameGrocery: 'Spices',
        imgGrocery: 'https://assets.epicurious.com/photos/5ea734df987eaf00089985db/16:9/w_2560%2Cc_limit/GroundWholeSpices_HERO_041620_6616.jpg',
        colorCode: '0xFFFFCCBC',
        descriptionGrocery: 'A spice is a seed, fruit, root, bark, or other plant substance primarily used for flavoring or coloring food. Spices are distinguished from herbs, which are the leaves, flowers, or stems of plants used for flavoring or as a garnish.',
      ),
      Category(
          name: "Orange",
          imgName: "assets/image/orange.jpg",
          price: "2.99",
          subCategories: [],
          description: '2 kg',
        vegImg: 'https://media.istockphoto.com/photos/single-fresh-broccoli-isolated-on-white-background-picture-id1176585619?k=20&m=1176585619&s=170667a&w=0&h=Ct3QGzPSRkb38ziE9POOKK7TR-UkuaTMq5RCpeKFWm0=',
        vegDescription: '1 pc',
        vegPrice: '2.99',
        vegName: 'Broccoli',
        meatDesc: '1 kg',
        meatName: 'Rabbit Meat',
        meatPrice: '3.99',
        meatImg: 'https://media.istockphoto.com/photos/raw-meat-rabbit-picture-id1146299339?k=20&m=1146299339&s=612x612&w=0&h=QEeZVPhROdxe7_O98t2SWe5ZGYZQPly-NwMLsfKiisk=',
        nameGrocery: 'Dairy',
        imgGrocery: 'https://simplyfresh.info/wp-content/uploads/2015/09/simply-handlingdairy.jpg',
        colorCode: '0xFFFFE0B2',
        descriptionGrocery: 'Dairy products or milk products, also known as lacticinia, are food products made from milk. The most common dairy animals are cow, water buffalo, nanny goat, and ewe. Dairy products include common grocery store food items in the Western world such as yogurt, cheese and butter.',
      ),
    ];
  }
}